// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPIStudyGuide.EntityFramework.Context.Other;

namespace RestAPIStudyGuide.Migrations
{
    [DbContext(typeof(CityInfoDBContext))]
    [Migration("20190219001805_CityInfoDBAddPointOfInterestDescription")]
    partial class CityInfoDBAddPointOfInterestDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestAPIStudyGuide.Models.Other.CityDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("RestAPIStudyGuide.Models.Other.PointOfInterestDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityDtoId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CityDtoId");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("RestAPIStudyGuide.Models.Other.PointOfInterestDto", b =>
                {
                    b.HasOne("RestAPIStudyGuide.Models.Other.CityDto")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityDtoId");
                });
#pragma warning restore 612, 618
        }
    }
}
